server:
  servlet:
    context-path: /bizagi
  port: 5002

servicios:
  uriCrearCaso: https://premiercredit.co/Originacion2019/WebServices/WorkflowEngineSOA?WSDL
  trustStore: C:/clientes/samtel.jks
  trustStorePassword: SAMTEL
  keyStore: C:/clientes/samtel.jks
  keyStorePassword: SAMTEL
